# https://taskfile.dev

version: '3'

vars:
  DUCKDB_VERSION: "0.10.2"

tasks:
  default:
    cmds:
      - task: build
    silent: true

  build:
    desc: "Build ducktest executable"
    cmds:
      - echo "Building ducktest..."
      - gcc -O2 -std=c99 ducktest.c -lduckdb -o ducktest
      - echo "Build complete"
    sources:
      - ducktest.c
    generates:
      - ducktest

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -f ducktest

  test:
    desc: "Run basic test"
    deps:
      - build
    cmds:
      - echo "Creating test database..."
      - ./ducktest init test.ddb --count 100k --size 10k --variance 2k
      - echo "Running performance test..."
      - ./ducktest run test.ddb --count 100k
      - echo "Test complete"

  install-deps:
    desc: "Install DuckDB development package (Ubuntu/Debian)"
    cmds:
      - echo "Installing DuckDB development package..."
      - sudo apt-get update
      - sudo apt-get install -y libduckdb-dev

  help:
    desc: "Show ducktest help"
    deps:
      - build
    cmds:
      - ./ducktest
